COMPOSE := docker compose --env-file .env -f deploy/compose.yaml

.PHONY: help
help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

.PHONY: check
check: fmt vet test ## Format, vet and test

.PHONY: fmt
fmt: ## gofmt every package
	@gofmt -l -w .

.PHONY: vet
vet: ## go vet
	@go vet ./...

.PHONY: test
test: ## Run the Go test suite (starts its own Postgres unless AZIR_TEST_DATABASE_URL is set)
	@go test ./... -race -count=1

.PHONY: test-db
test-db: ## Reuse the running Postgres for tests instead of starting a container
	@$(COMPOSE) up -d postgres
	@until docker exec azir-db pg_isready -U azir -d azir >/dev/null 2>&1; do sleep 1; done
	@docker exec azir-db psql -U azir -d azir -c "CREATE DATABASE azir_test" 2>/dev/null || true
	@. ./.env && echo "export AZIR_TEST_DATABASE_URL=\"postgres://azir:$$POSTGRES_PASSWORD@localhost:5433/azir_test?sslmode=disable\""

.PHONY: psql
psql: ## Open a psql session against the running database
	@docker exec -it azir-db psql -U azir -d azir

.PHONY: build
build: ## Build all binaries into bin/
	@go build -o bin/ ./cmd/...

# Every secret the stack needs, as name:generator pairs.
#
# One list so that adding a service means adding a line here, and an existing
# deployment picks the new value up on its next `make up` rather than failing
# to start on a variable that did not exist when its .env was written.
.PHONY: init
init: ## Generate any missing secrets in .env (never rewrites one that exists)
	@umask 077; \
	touch .env; \
	added=""; \
	add() { \
	  if ! grep -q "^$$1=" .env; then \
	    [ -n "$$3" ] && echo "$$3" >> .env; \
	    echo "$$1=$$2" >> .env; \
	    added="$$added $$1"; \
	  fi; \
	}; \
	if [ ! -s .env ]; then \
	  echo "# Generated by \`make init\`. Not in version control — a secret in a" >> .env; \
	  echo "# repository is a secret everyone who clones it now has." >> .env; \
	fi; \
	add POSTGRES_PASSWORD "$$(openssl rand -hex 24)" ""; \
	add AZIR_MASTER_KEY "$$(openssl rand -base64 32)" \
	  "# Every stored credential is sealed with this. Lose it and the vault cannot be read."; \
	add SEARXNG_SECRET "$$(openssl rand -hex 32)" \
	  "# Signs SearXNG's own sessions. It never sees a customer credential."; \
	add AZIR_SMOKE_EMAIL "smoke@azir.local" \
	  "# Used only by scripts/smoke.sh against a development stack."; \
	add AZIR_SMOKE_PASSWORD "$$(openssl rand -base64 18)" ""; \
	if [ -n "$$added" ]; then \
	  echo "generated:$$added"; \
	else \
	  echo ".env already has every secret the stack needs"; \
	fi

.PHONY: up
up: init ## Start the full stack
	@$(COMPOSE) up --build -d

.PHONY: down
down: ## Stop the stack
	@$(COMPOSE) down

.PHONY: down-hard
down-hard: ## Stop the stack and delete its data, returning it to first run
	@$(COMPOSE) down -v

.PHONY: logs
logs: ## Tail stack logs
	@$(COMPOSE) logs -f

.PHONY: smoke
smoke: ## Verify discovery and a tool round-trip against a running stack
	@./scripts/smoke.sh

.PHONY: keygen
keygen: ## Generate a master key for AZIR_MASTER_KEY
	@openssl rand -base64 32
